[project]
name = "lab1-robust-ml-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=1.5.0",
    "scikit-learn>=1.8.0",
    "torch>=2.0.0"
]
